// Code generated by hand for tests. DO NOT EDIT.

package exempt

// generated has a long doc.
// Two.
// Three.
// Four.
func generated() {}

// generatedVar has a long doc.
// Two.
// Three.
var generatedVar = 1
